### ISSUE TITLE
Log4netSocketAppender.dll doesn't work whenever logstash service restart

### ISSUE THREAD

**Issue by funbrain** [ugurozsahin/log4net-socket-appender#1]
hi there

I run logstash as a service in window server.
I use tcp input, grok filter, amazon_es output in my logstash config.
I stream .net application logs using Log4netSocketAppender to logstash host.
My app logs send continuously to logstash.

problem is that i restart logstash service then... no more logs come to logstash. 
then i copy and replace Log4netSocketAppender.dll in app.
very strange, logs come back to logstash 
I try like 3 times, it's same 

may i know why Log4netSocketAppender.dll doesn't work whenever logstash service restart??????

i m running logstash v6.1.1.

**Comment by ugurozsahin** [comment]
I apologize for the delay.

I think I found the problem.
Having to open the socket one time may have caused the problem.
I can re-open the connection by checking if the socket connection is closed.

**Comment by funbrain** [comment]
Thank you for reply @ugurozsahin  

so, i am waiting next version... 😄

**Comment by funbrain** [comment]
is that possible to reconnect after connection lost(10 mins later) via Log4netSocketAppender webconfig?

**Comment by funbrain** [comment]
i play ConAttempts setting, it works for me
eg:

```
<ConAttemptsCount value="10" />
<ConAttemptsWaitingTimeMilliSeconds value="60000" />
```

```
<ConAttemptsCount value="5" />
<ConAttemptsWaitingTimeMilliSeconds value="600000" />
```
